#!name=TIDAL
#!desc=解锁 HiFi Plus 权限

[Script]

TIDALHiFiPlusCrack = type=http-response, pattern=^https?:\/\/api\.tidal\.com\/v1\/users\/\d+\/subscription.+, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/PJxiaowangzi/Dsj/main/2004/TIDALHiFiPlusCrack.js, timeout=60, script-update-interval=0
TIDALMasterCrack = type=http-request, pattern=^https?:\/\/api\.tidal\.com\/v1\/tracks/\d+\/playbackinfopostpaywall.+, requires-body=true, max-size=3145728, script-path=https://raw.githubusercontent.com/PJxiaowangzi/Dsj/main/Dj2047/tidal.js, timeout=60, script-update-interval=0

[MITM]
hostname = %APPEND% api.tidal.com
